### ISSUE TITLE
Saving weights

### ISSUE THREAD

**Issue by aviniciux** [FarisNolan/Neural_Algorithm_Artistic_Style#1]
I see your code performs two loops: one for training and another one to create the output image from the previous training. How can I save the weights at the end of training in order to use it as a style model for other images, such that I don't need to run the training anymore? Tkx,

**Comment by FarisNolan** [comment]
Hi there,
Sorry for the eternal lack of reply. I'm sure this is no longer of any use to you, but unfortunately there is no way to save the weights of the network for a specific style image. The reason for this is that the back-propagation is performed using the pixels of the blank input image as parameters, meaning that the final "weights" are in fact the pixel values in the output image rather than a series of weights which can be used in a neural network.
I hope that makes some sort of sense. Thanks for your interest!
